#define extended_resolution 256
#define input_file_name "../data/81.txt"
#define blobDetection false
#define contourDetection true  // add comments to eveything and sperate in sections
#define colorMap true
#define scaleImage true
#define showImage true
#define blobMinThreshold 12
#define blobMaxThreshold 25
#define blobThresholdStep 1
#define minDistBetweenBlobs 4
#define blobFilterByArea true
#define blobMinArea 2
#define blobMaxArea 5000
#define blobFilterByCircularity false
#define blobMinCircularity 0.1
#define blobMaxCircularity 1
#define blobFilterByConvexity false
#define blobMinConvexity 0.87
#define blobMaxConvexity 1
#define blobFilterByInertia false
#define blobMinInertiaRatio 0.01
#define blobMaxInertiaRatio 1
#define blobFilterByColor false
#define blobColor 255
#define RECTMAXAREA 200000
#define RECTMINAREA 5
#define INTEREST_THRESH 1
#define START_FRAME 100
#define END_FRAME 600
#define LIVE false
#define PRINT_FRAME false
#define WAIT_TIME 100
